//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POGClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IPOGService", CallbackContract=typeof(POGClient.ServiceReference.IPOGServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IPOGService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOGService/Connect", ReplyAction="http://tempuri.org/IPOGService/ConnectResponse")]
        void Connect(Common.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOGService/Connect", ReplyAction="http://tempuri.org/IPOGService/ConnectResponse")]
        System.Threading.Tasks.Task ConnectAsync(Common.Client client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IPOGService/Disconnect")]
        void Disconnect(long id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IPOGService/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOGService/GetClients", ReplyAction="http://tempuri.org/IPOGService/GetClientsResponse")]
        System.Collections.Generic.List<Common.Client> GetClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOGService/GetClients", ReplyAction="http://tempuri.org/IPOGService/GetClientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Common.Client>> GetClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOGService/GetMessages", ReplyAction="http://tempuri.org/IPOGService/GetMessagesResponse")]
        System.Collections.Generic.List<Common.Message> GetMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOGService/GetMessages", ReplyAction="http://tempuri.org/IPOGService/GetMessagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Common.Message>> GetMessagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPOGService/Say")]
        void Say(Common.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPOGService/Say")]
        System.Threading.Tasks.Task SayAsync(Common.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPOGService/IsWriting")]
        void IsWriting(long client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPOGService/IsWriting")]
        System.Threading.Tasks.Task IsWritingAsync(long client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPOGServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPOGService/RefreshClients")]
        void RefreshClients(System.Collections.Generic.List<Common.Client> clients);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPOGService/Receive")]
        void Receive(Common.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPOGService/IsWritingCallback")]
        void IsWritingCallback(long client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPOGService/UserJoin")]
        void UserJoin(Common.Client client);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPOGService/UserLeave")]
        void UserLeave(Common.Client client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPOGServiceChannel : POGClient.ServiceReference.IPOGService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class POGServiceClient : System.ServiceModel.DuplexClientBase<POGClient.ServiceReference.IPOGService>, POGClient.ServiceReference.IPOGService {
        
        public POGServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public POGServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public POGServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public POGServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public POGServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect(Common.Client client) {
            base.Channel.Connect(client);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(Common.Client client) {
            return base.Channel.ConnectAsync(client);
        }
        
        public void Disconnect(long id) {
            base.Channel.Disconnect(id);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(long id) {
            return base.Channel.DisconnectAsync(id);
        }
        
        public System.Collections.Generic.List<Common.Client> GetClients() {
            return base.Channel.GetClients();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Common.Client>> GetClientsAsync() {
            return base.Channel.GetClientsAsync();
        }
        
        public System.Collections.Generic.List<Common.Message> GetMessages() {
            return base.Channel.GetMessages();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Common.Message>> GetMessagesAsync() {
            return base.Channel.GetMessagesAsync();
        }
        
        public void Say(Common.Message msg) {
            base.Channel.Say(msg);
        }
        
        public System.Threading.Tasks.Task SayAsync(Common.Message msg) {
            return base.Channel.SayAsync(msg);
        }
        
        public void IsWriting(long client) {
            base.Channel.IsWriting(client);
        }
        
        public System.Threading.Tasks.Task IsWritingAsync(long client) {
            return base.Channel.IsWritingAsync(client);
        }
    }
}
